# Generated by Django 4.2.24 on 2025-09-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.BinaryField()),
                ('token', models.CharField(blank=True, max_length=40, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_key', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company_group',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'account_group',
                'managed': False,
            },
        ),
    ]
